language: csharp
solution: IotaApi.sln
install:
- nuget restore IotaApi.sln
- nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
- xbuild /p:Configuration=Release IotaApi.sln
- mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./IotaCSharpApiUnitTests/bin/Release/IotaCSharpApiUnitTests.dll
deploy:
  provider: script
  skip_cleanup: true
  script: cd iota.lib.csharp && nuget pack ./IotaCSharpApi/IotaCSharpApi.csproj -Version $VERSION -IncludeReferencedProjects -Prop Configuration=Release && nuget push *.nupkg $NUGET_API_KEY -verbosity detailed
  tags: true
  repo: iotaledger/iota.lib.csharp
  all_branches: true