language: csharp
solution: IotaApi.sln
install:
- nuget restore IotaApi.sln
- nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
script:
- xbuild /p:Configuration=Release IotaApi.sln
- mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./IotaCSharpApiUnitTests.Tests/bin/Release/IotaCSharpApiUnitTests.dll
